@startuml
title test_pull_request
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
hnote over master: GitVersion: 0.1.0
master --> master: TAG: 0.1.0
ref over master: 0.1.0
master ->> pr.1: checkout
hnote over pr.1: SCM version: 0.1.0
pr.1 --> pr.1: change
pr.1 -> pr.1: commit
hnote over pr.1: GitVersion: 0.1.1a1
hnote over pr.1: SCM version: 0.1.1.dev1+gde29cf8
pr.1 --> pr.1: TAG: 0.1.1a1
ref over pr.1: 0.1.1a1
hnote over pr.1: GitVersion: 0.1.1a1
hnote over pr.1: SCM version: 0.1.1a1
pr.1 --> pr.1: change
hnote over pr.1: GitVersion: 0.1.1a1
hnote over pr.1: SCM version: 0.1.1a2.dev0+gde29cf8.d20180121
pr.1 -> pr.1: commit
hnote over pr.1: GitVersion: 0.1.1a2
hnote over pr.1: SCM version: 0.1.1a2.dev1+ga4fec93
@enduml