@startuml
title test_release
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
hnote over master: GitVersion: 0.1.0
master --> master: TAG: 0.1.0
ref over master: 0.1.0
master ->> release.test: checkout
hnote over release.test: SCM version: 0.1.0
release.test --> release.test: change
release.test -> release.test: commit
hnote over release.test: GitVersion: 0.1.1rc1
hnote over release.test: SCM version: 0.1.1.dev1+g5c5a3cf
release.test --> release.test: TAG: 0.1.1rc1
ref over release.test: 0.1.1rc1
hnote over release.test: GitVersion: 0.1.1rc1
hnote over release.test: SCM version: 0.1.1rc1
release.test --> release.test: change
hnote over release.test: GitVersion: 0.1.1rc1
hnote over release.test: SCM version: 0.1.1rc2.dev0+g5c5a3cf.d20180121
release.test -> release.test: commit
hnote over release.test: GitVersion: 0.1.1rc2
hnote over release.test: SCM version: 0.1.1rc2.dev1+ge0d280e
release.test ->> release.0.2.0: checkout
hnote over release.0.2.0: GitVersion: 0.2.0
hnote over release.0.2.0: SCM version: 0.1.1rc2.dev1+ge0d280e
release.0.2.0 --> release.0.2.0: TAG: 0.2.0
ref over release.0.2.0: 0.2.0
hnote over release.0.2.0: GitVersion: 0.2.0
hnote over release.0.2.0: SCM version: 0.2.0
@enduml