@startuml
title test_master
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
hnote over master: GitVersion: 0.1.0
master --> master: TAG: 0.1.0
ref over master: 0.1.0
hnote over master: SCM version: 0.1.0
master --> master: change
master -> master: commit
hnote over master: GitVersion: 0.1.1
hnote over master: SCM version: 0.1.1.dev1+ge0d43e5
master --> master: change
hnote over master: GitVersion: 0.1.1
hnote over master: SCM version: 0.1.1.dev1+ge0d43e5.d20180121
master -> master: commit
hnote over master: GitVersion: 0.1.1
master --> master: TAG: 0.1.1
ref over master: 0.1.1
hnote over master: GitVersion: 0.1.1
hnote over master: SCM version: 0.1.1
@enduml