@startuml
title test_flow_release
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
master --> master: TAG: 0.1.0
ref over master: 0.1.0
master ->> develop: checkout
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
develop --> develop: change
develop -> develop: commit
hnote over develop: GitVersion: 0.1.1b10
hnote over develop: SCM version: 0.1.1.dev10+g4abf3af
develop ->> release.0.1.1: checkout
hnote over release.0.1.1: GitVersion: 0.1.1rc10
hnote over release.0.1.1: SCM version: 0.1.1.dev10+g4abf3af
release.0.1.1 --> release.0.1.1: change
release.0.1.1 -> release.0.1.1: commit
release.0.1.1 --> release.0.1.1: TAG: 0.1.1rc11
ref over release.0.1.1: 0.1.1rc11
hnote over release.0.1.1: GitVersion: 0.1.1rc11
hnote over release.0.1.1: SCM version: 0.1.1rc11
release.0.1.1 ->> develop: checkout
release.0.1.1 ->o develop: merge
hnote over develop: GitVersion: 0.1.1b11
hnote over develop: SCM version: 0.1.1rc11
develop ->> master: checkout
release.0.1.1 ->o master: merge
hnote over master: GitVersion: 0.1.1
hnote over master: SCM version: 0.1.1rc11
master --> master: TAG: 0.1.1
ref over master: 0.1.1
hnote over master: GitVersion: 0.1.1
hnote over master: SCM version: 0.1.1
master ->> develop: checkout
hnote over develop: GitVersion: 0.1.1
hnote over develop: SCM version: 0.1.1
develop --> develop: change
develop -> develop: commit
hnote over develop: GitVersion: 0.1.2b1
hnote over develop: SCM version: 0.1.2.dev1+gc03cbf7
@enduml