@startuml
title test_feature
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
hnote over master: GitVersion: 0.1.0
master --> master: TAG: 0.1.0
ref over master: 0.1.0
master ->> feature.test: checkout
hnote over feature.test: SCM version: 0.1.0
feature.test --> feature.test: change
feature.test -> feature.test: commit
hnote over feature.test: GitVersion: 0.1.1a1
hnote over feature.test: SCM version: 0.1.1.dev1+g4feb22d
feature.test --> feature.test: TAG: 0.1.1a1
ref over feature.test: 0.1.1a1
hnote over feature.test: GitVersion: 0.1.1a1
hnote over feature.test: SCM version: 0.1.1a1
feature.test --> feature.test: change
hnote over feature.test: GitVersion: 0.1.1a1
hnote over feature.test: SCM version: 0.1.1a2.dev0+g4feb22d.d20180121
feature.test -> feature.test: commit
hnote over feature.test: GitVersion: 0.1.1a2
hnote over feature.test: SCM version: 0.1.1a2.dev1+g58c8498
@enduml