@startuml
title test_develop
skinparam ParticipantPadding 20
skinparam BoxPadding 10
participant master
hnote over master: GitVersion: 0.1.0
master --> master: TAG: 0.1.0
ref over master: 0.1.0
master ->> develop: checkout
hnote over develop: SCM version: 0.1.0
develop --> develop: change
develop -> develop: commit
hnote over develop: GitVersion: 0.1.1b1
hnote over develop: SCM version: 0.1.1.dev1+g558be9b
develop --> develop: TAG: 0.1.1b1
ref over develop: 0.1.1b1
hnote over develop: SCM version: 0.1.1b1
develop --> develop: change
hnote over develop: GitVersion: 0.1.1b1
hnote over develop: SCM version: 0.1.1b2.dev0+g558be9b.d20180121
develop -> develop: commit
hnote over develop: GitVersion: 0.1.1b2
hnote over develop: SCM version: 0.1.1b2.dev1+gb3088be
@enduml